// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdlkoqdzqzelzgtrwtyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbGtvcWR6cXplbHpndHJ3dHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDI4MDYsImV4cCI6MjA4ODcxODgwNn0.H6eOEnMGKMKL26yE8_mFxWQn19BYqm8-Suv5zpGYbhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});